### ISSUE TITLE
Issues in one topic

### ISSUE THREAD

**Issue by psxsahan** [XBoom31/ApocalyseCheatsSC#10]
skinchanger Knifes sometimes bugging
player chams  color not changes in menu
hitbox buggy. cant shoot some body parts

**Comment by CyclesProgramming** [comment]
#11

**Comment by psxsahan** [comment]
@CyclesProgramming  ty but did you fix hitbox? o.O

**Comment by psxsahan** [comment]
Terror esp box visible / non visible color not change
