### ISSUE TITLE
got vacban

### ISSUE THREAD

**Issue by madlifer** [XBoom31/ApocalyseCheatsSC#15]
https://gyazo.com/3dd6474d6d168a27fbf8536f35266535
https://gyazo.com/6443f2d08d094adfd6ecdb89aef8876d
   Anyone read this post do FUCKING NOT tell me its an OWban ，its ur problem  something shit . 
         its a overwatchban with yellowbar  ，I'm sure this is an VACBan not a OWban. this acc never use any cheat excpet AC Source Cheats
        i am finding a way to add something shit  from two days ago So I did not play the game，10 hours  ago my friend told me he got a OW ban （use  ACcheat  a guy post on MPGAY ）, I thought he was too unrestrained or that guy do sothing worry. So I went to a game ，got ban in game too :(  . Also got a this OWBan with YellowBar I use ur new update source 。
       So，I think its this Cheat got delected . My another friend（P2c AyywareCheat Maker） told me “CreateMoveClient_Hooked“ got delected, but i am not good at Cpp ， So I think u can make its UD again？

**Comment by otvv** [comment]
lmao

**Comment by CyclesProgramming** [comment]
yes first u say what u just did in English or properly in your native language

**Comment by psxsahan** [comment]
you need your make undetected hack with junk code.

**Comment by getaropeandhangyourselfwithit** [comment]
🤔
