### ISSUE TITLE
Something shit i added May be u want it

### ISSUE THREAD

**Issue by madlifer** [XBoom31/ApocalyseCheatsSC#16]
**1.//ESPBOX: corner&full choose** 
Change this to esp.cpp  find  void CEsp::DrawBox(CEsp::ESPBox size, Color color)

- 	

> if (Menu::Window.VisualsTab.BoxDesign.GetIndex() == 0)
> 	{
> 		// Corner Box
> 		int VertLine = (((float)size.w) * (0.20f));
> 		int HorzLine = (((float)size.h) * (0.20f));
> 
> 		Render::Clear(size.x, size.y - 1, VertLine, 1, Color(10, 10, 10, 150));
> 		Render::Clear(size.x + size.w - VertLine, size.y - 1, VertLine, 1, Color(10, 10, 10, 150));
> 		Render::Clear(size.x, size.y + size.h - 1, VertLine, 1, Color(10, 10, 10, 150));
> 		Render::Clear(size.x + size.w - VertLine, size.y + size.h - 1, VertLine, 1, Color(10, 10, 10, 150));
> 
> 		Render::Clear(size.x - 1, size.y, 1, HorzLine, Color(10, 10, 10, 150));
> 		Render::Clear(size.x - 1, size.y + size.h - HorzLine, 1, HorzLine, Color(10, 10, 10, 150));
> 		Render::Clear(size.x + size.w - 1, size.y, 1, HorzLine, Color(10, 10, 10, 150));
> 		Render::Clear(size.x + size.w - 1, size.y + size.h - HorzLine, 1, HorzLine, Color(10, 10, 10, 150));
> 
> 		Render::Clear(size.x, size.y, VertLine, 1, color);
> 		Render::Clear(size.x + size.w - VertLine, size.y, VertLine, 1, color);
> 		Render::Clear(size.x, size.y + size.h, VertLine, 1, color);
> 		Render::Clear(size.x + size.w - VertLine, size.y + size.h, VertLine, 1, color);
> 
> 		Render::Clear(size.x, size.y, 1, HorzLine, color);
> 		Render::Clear(size.x, size.y + size.h - HorzLine, 1, HorzLine, color);
> 		Render::Clear(size.x + size.w, size.y, 1, HorzLine, color);
> 		Render::Clear(size.x + size.w, size.y + size.h - HorzLine, 1, HorzLine, color);
> 	}
> 	else if (Menu::Window.VisualsTab.BoxDesign.GetIndex() == 1)
> 	{
> 		// Full Box
> 		Render::Outline(size.x, size.y, size.w, size.h, color);
> 		Render::Outline(size.x - 1, size.y - 1, size.w + 2, size.h + 2, Color(10, 10, 10, 150));
> 		Render::Outline(size.x + 1, size.y + 1, size.w - 2, size.h - 2, Color(10, 10, 10, 150));
> 	}

**2.//ArmorBar （Side bar Style）**

-

>  void CEsp::DrawArmor(IClientEntity* pEntity, CEsp::ESPBox size)
> {
> 	ESPBox ArmorBar = size;
> 	ArmorBar.y += (ArmorBar.h + 6);
> 	ArmorBar.h = 4;
> 
> 	float ArmorValue = pEntity->ArmorValue();
> 	float ArmorPerc = ArmorValue / 100.f;
> 	float Width = (size.w * ArmorPerc);
> 	ArmorBar.w = Width;
> 
> 	int armor = pEntity->ArmorValue();
> 
> 	if (armor > 100)
> 		armor = 100;
> /* I dont want a change  yellow is good */
> 	//int r = 255 - armor * 2.55;
> 	//int g = armor * 2.55;
> 
> 	int armorBar = size.h / 100 * armor;
> 	int armorBarDelta = size.h - armorBar;
> 
> 	Render::Clear(size.x - 5, size.y - 1, 4, size.h + 2, Color(0, 0, 0, 150));
> 	Render::Clear(size.x - 4, size.y + 1, 2, size.h * 0.01 * armor, Color(255, 255, 0, 255));
> }

**3.// Distence** 

> - void CEsp::DrawDistanse(IClientEntity* pEntity, CEsp::ESPBox size)
> {
> 	IClientEntity *pLocal = hackManager.pLocal();
> 
> 	Vector vecOrigin = pEntity->GetOrigin();
> 	Vector vecOriginLocal = pLocal->GetOrigin();
> 	static RECT defSize = Render::GetTextSize(Render::Fonts::Default, "");
> 
> 	char dist_to[32];
> 	sprintf_s(dist_to, "%.0fm", DistanceTo(vecOrigin, vecOriginLocal));
> 
> 	Render::Text(size.x + size.w + 3, size.y + (0.6*(defSize.bottom + 28)), Color(255, 255, 255, 255), Render::Fonts::ESP, dist_to);
> }
> 
> float CEsp::DistanceTo(Vector vecDst, Vector vecSrc)
> {
> 	Vector vDelta = vecDst - vecSrc;
> 
> 	float fDistance = ::sqrtf((vDelta.Length()));
> 
> 	if (fDistance < 1.0f)
> 		return 1.0f;
> 
> 	return fDistance;
> }
**Now U got this https://gyazo.com/c4787acaf8f2707dff06b23f59ee18af **
**and this https://gyazo.com/b94679c963a34ec1f3c9911c1da5250f**
**4.show an info if someone watching u**
find `if (Interfaces::Engine->GetPlayerInfo(pTarget->GetIndex(), &pinfo2))`
Add this 
- 
								if (pTarget->GetIndex() == pLocal->GetIndex())
								{
									RECT TextSizeD = Render::GetTextSize(Render::Fonts::Default, "这位先生,请开始你的表演!(SomeOne is Watching U)");
									Render::Text(scrn.right / 2 - TextSizeD.right / 2 - 4, scrn.bottom / 2 + 30, Color(240, 70, 80, 255), Render::Fonts::Default, "这位先生,请开始你的表演!(SomeOne is Watching U)");
								}
**5. Add SkyBox**
go to hooks.cpp find this line `	if (Interfaces::Engine->IsInGame())`
Add this

> - 
> 	if (Interfaces::Engine->IsInGame())
> 	{
> 		ConVar* postprocessing = Interfaces::CVar->FindVar("sv_skyname");
> 		if (Menu::Window.VisualsTab.SkyStyle.GetIndex() == 0)
> 		{
> 			//postprocessing->SetValue("cs_baggage_skybox_");
> 		}
> 		else if (Menu::Window.VisualsTab.SkyStyle.GetIndex() == 1)
> 		{
> 			postprocessing->SetValue("jungle");
> 		}
> 		else if (Menu::Window.VisualsTab.SkyStyle.GetIndex() == 2)
> 		{
> 			postprocessing->SetValue("vietnam");
> 		}

The other thing i added to make this cheat support Chinese ，I dont think  its will cause cheat delected
only Utf8ToAscii 

that is all my changed , What is the reason  make me got vac？ 
onething i am not sure its skybox shit.

**Comment by CyclesProgramming** [comment]
Well this src is detected and you will probably need to do ALOT more to make it non vac detected and if ur csgo is chinese the chinese shouldnt vac you

**Comment by madlifer** [comment]
what mean src ALOT？  i dont know good english plz make its clear buddy 

I might find why i got vac   ，Xenos Injector maybe delected  

i will test it , use another injector

**Comment by otvv** [comment]
XenosInjector is detected. 
Don't use Xenos or Extreme Injector, code your own injector.

EDIT: The source-code isn't detected.

**Comment by madlifer** [comment]
Yeah  got3+ acc baned using 3 types cheat now i know that injector delected :()
