### ISSUE TITLE
Fps drop to 10

### ISSUE THREAD

**Issue by psxsahan** [XBoom31/ApocalyseCheatsSC#22]
Fps drop to 10 sometimes and config saver not working

**Comment by psxsahan** [comment]
Config not saving

**Comment by CyclesProgramming** [comment]
Turn off hit scan if you have a bad pc
cfgs are working for me

**Comment by psxsahan** [comment]
@CyclesProgramming i have gtx 1080 and i7 6700k lmao..

**Comment by getaropeandhangyourselfwithit** [comment]
dood thats shit pc

**Comment by moneyfraud** [comment]
Configs may not work if your Tab names have spaces in them. It needs to be a one word.
