### ISSUE TITLE
Hitchance is broken

### ISSUE THREAD

**Issue by lightstepcpp** [XBoom31/ApocalyseCheatsSC#25]
Hello, your hitchance is broken, to fix this simply go to Entities.h and replace
	float GetInaccuracy()
	{
		typedef float(__thiscall* oInaccuracy)(PVOID);
		return call_vfunc< oInaccuracy >(this, 484)(this);
	}
with
	float GetInaccuracy()
	{
		typedef float(__thiscall* oInaccuracy)(PVOID);
		return call_vfunc< oInaccuracy >(this, 483)(this);
	}

**Comment by XBoom31** [comment]
Thanks!
