### ISSUE TITLE
Charms problem 

### ISSUE THREAD

**Issue by Petrju** [XBoom31/ApocalyseCheatsSC#27]
Visual Charms not worked

**Comment by XBoom31** [comment]
you mean visual only?

**Comment by Petrju** [comment]
yes

**Comment by Petrju** [comment]
When i start chams visual only enemy and my team hide they are ghosts

**Comment by XBoom31** [comment]
yeah, was a test, i forgot to delete them from menu, forget them.

**Comment by Dimitriblyater** [comment]
Also chams doesnt disable for team while having enemies only enabled

**Comment by Petrju** [comment]
Man plz add only visual chams u want play legit 😂😃
