### ISSUE TITLE
Knifechanger problem "ShadowDaggers icon wont appear FIX"

### ISSUE THREAD

**Issue by eeioruewo0iruwe** [XBoom31/ApocalyseCheatsSC#29]
else if (Model == 10) // Shadow Daggers
								{
									*pWeapon->ModelIndex() = iDagger; // m_nModelIndex
									*pWeapon->ViewModelIndex() = iDagger;
									*pWeapon->WorldModelIndex() = iDagger + 1;
									*pWeapon->m_AttributeManager()->m_Item()->ItemDefinitionIndex() = 516;
									

should be

else if (Model == 9) // Shadow Daggers
								{
									*pWeapon->ModelIndex() = iDagger; // m_nModelIndex
									*pWeapon->ViewModelIndex() = iDagger;
									*pWeapon->WorldModelIndex() = iDagger + 1;
									*pWeapon->m_AttributeManager()->m_Item()->ItemDefinitionIndex() = 516;

**Comment by XBoom31** [comment]
nice :)
