### ISSUE TITLE
Text ESP

### ISSUE THREAD

**Issue by Dimitriblyater** [XBoom31/ApocalyseCheatsSC#33]
This is not an issue but a request for assistance.

I would like to change where text esp like weapon esp is drawn next to the player.
Can someone show me where to change? :)

**Comment by eeioruewo0iruwe** [comment]
I believe this is what you are looking for

https://gyazo.com/98711ea6c709de903cf9def0303076a5

if not then my b

**Comment by Dimitriblyater** [comment]
I know that, just don't know exactly where to change it xd

**Comment by eeioruewo0iruwe** [comment]
if u were changing the location of it, i believe it would be here.
https://gyazo.com/6bb27b2ecb9ac611c14890faa7ce12b1

Its located under DrawInfo

**Comment by Dimitriblyater** [comment]
I think that code is for multiple text esps? + Your code is different from the github

I like the weapon esp you added :D
