### ISSUE TITLE
Nightmode

### ISSUE THREAD

**Issue by Dimitriblyater** [XBoom31/ApocalyseCheatsSC#34]
I saw a nightmode option then checked the code and there was no code for it xD?

Can you can paste in nightmode?
https://www.unknowncheats.me/forum/counterstrike-global-offensive/215804-night-mode.html

**Comment by eeioruewo0iruwe** [comment]
There is a night mode, just that there are unnecessary checks and that breaks the function... but regardless u get massive lag spikes the way it is right now so its best that there isnt a night mode until there is a fix for the lag. the lag comes from the console spam CMaterial:Precache garbage.
