### ISSUE TITLE
Incorrect bHasAA variable definition

### ISSUE THREAD

**Issue by 0x344** [XBoom31/ApocalyseCheatsSC#36]
https://github.com/XBoom31/ApocalyseCheatsSC/blob/master/AYYWARE%20CSGO/AntiAntiAim.cpp#L31
((*flPitch == 90.0f) shoulde be 89.0f, not 90.0f

**Comment by DarkAussieYT** [comment]
close this, issue was fixed in https://github.com/XBoom31/ApocalyseCheatsSC/pull/35
which has been merged
