### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dimitriblyater** [XBoom31/ApocalyseCheatsSC#37]
This
`@@ -0,0 +1,4732 @@`
gives an error on compile, i just removed it, idk what it does.

**Comment by XBoom31** [comment]
wtf is that

**Comment by Dimitriblyater** [comment]
you added it in recent commit https://github.com/XBoom31/ApocalyseCheatsSC/commit/d67fb01d2fcdaf39a7767ebbe8c9160a965709bb

**Comment by XBoom31** [comment]
paste the code what cause the error... how do you think i can fix it wihout knowing what's the error?

**Comment by Dimitriblyater** [comment]
I already said what causes the error on compile, its the first post on this page

**Comment by XBoom31** [comment]
oh sry im dumb xdddd, idk what is that, i did not added that shit

**Comment by Dimitriblyater** [comment]
then remove it xd

**Comment by DarkAussieYT** [comment]
https://github.com/XBoom31/ApocalyseCheatsSC/pull/38
fixes this, also i found it in menu.cpp too

**Comment by Dimitriblyater** [comment]
Ok, I wonder how that weird code got there xD
