### ISSUE TITLE
GlowEsp causing crash even after updating offset

### ISSUE THREAD

**Issue by Goobybear** [XBoom31/ApocalyseCheatsSC#39]
The GlowESP causes a crashed game even with the new offset of 0x4FA7660

**Comment by otvv** [comment]
The glow esp is fucked somehow. I "tried" to fix it, but 0 luck.

**Comment by DarkAussieYT** [comment]
that's the offset not the signature

**Comment by Goobybear** [comment]
Yeah ive tried aswell, He added one over the original but no luck getting his one to work, just insta crashes everytime.

**Comment by otvv** [comment]
I fixed the Glow esp. You need to add the glowmanager class. Also you I'll need to redo the entire glow code in ESP.cpp. If someone wants I can do a PR. But idk, Xboom isn't updating this cheat anymore so, idk if worth the effort to adapt my code for Apocalypse.

**Comment by DarkAussieYT** [comment]
Well maybe if he is busy you could still maintain this

**Comment by Goobybear** [comment]
Yeah if youre up for it please do a pull request Floody.

**Comment by XBoom31** [comment]
sorry for innactivity, i found someone special, i think you can understand this, ill give acces to commits to  @iFloody if he agree with that
https://github.com/XBoom31/ApocalyseCheatsSC/invitations

**Comment by otvv** [comment]
Yeah, when I get some time I'll push the GlowESP for Apocalypse. Thanks for the invitation Xboom.

**Comment by XBoom31** [comment]
can you debug that shit?
https://pastebin.com/4EJBfzyz

**Comment by otvv** [comment]
I'll try. What exactly is wrong?

**Comment by XBoom31** [comment]
i tried to make 'nearest hitbox' for the aimbot, and it crashes... idk why and idk how to debug it

**Comment by otvv** [comment]
You can use Visual Studio to debug it. Press CTRL+ALT+P and select CS:GO. (Do this while the DLL is injected) And see where it crashes on your code.

Btw, the GlowESP is ready. (It's not the best one but, it's working.)
![5756043d26e70a9fd26f9cd357508b56](https://user-images.githubusercontent.com/17851066/28241486-e6a1faa0-696b-11e7-9980-89049581c129.jpg)

**Comment by otvv** [comment]
I'm ready to push the commit. Pushing now.

**Comment by Dimitriblyater** [comment]
Errors on compile

1>ESP.cpp(297): error C2660: 'CEsp::DrawGlow': function does not take 1 arguments
1>ESP.cpp(863): error C2511: 'void CEsp::DrawGlow(Color)': overloaded member function not found in 'CEsp'
1>d:\apocalyse\ayyware csgo\ESP.h(6): note: see declaration of 'CEsp'
1>Done building project "AYYWARE CSGO.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by iFloody** [comment]
Lemme, see that.

**Comment by otvv** [comment]
Fixed, I missed to commit one file yesterday.

Pushing the commit now.

**Comment by XBoom31** [comment]
can you fix that legitbot i've sent you?

**Comment by otvv** [comment]
Is it the whole code?

I'll see what I can do.

**Comment by XBoom31** [comment]
it's broken since i tried to add nearest hitbox, can you fix it please?

**Comment by Dimitriblyater** [comment]
Thx for glow fix, would also like to see nearest hitbox

**Comment by otvv** [comment]
@XBoom31 can you send me your legit bot part of menu.cpp?

**Comment by XBoom31** [comment]
https://pastebin.com/evXDMTZf, theres the whole menu

**Comment by otvv** [comment]
It's crashing here: MathFunctions.cpp

![](https://i.gyazo.com/3ad13133d35f0da3b86ea78910634fde.png) 
No clue what is wrong.

**Comment by otvv** [comment]
Probably is something here, that is wrong idk.
![](https://i.gyazo.com/734cddef3c8b5f0e457f3b362965b230.png)

**Comment by XBoom31** [comment]
FovToPlayer is working, is the same as before

**Comment by otvv** [comment]
Yeah, I just realized that. 
It's something with the MathFunctions.cpp (Vectors and shit). I tried another code but it's crashing too. In AC and in my cheat. Idk how to fix it. I'll try later but, I don't guarantee anything.

**Comment by XBoom31** [comment]
nothing is wrong there, i edited only legitbot.cpp

**Comment by otvv** [comment]
I'm working on a new code for a multihitbox/nearest hitbox for the legitbot. I'm testing it rn, but isn't crashing kek. It's a much more simplier code than the one that you are working it. I'll do some more testings, check if wasn't any bugs, etc. And if you want I can help you with the code.

**Comment by Dimitriblyater** [comment]
any news guys ? :)

**Comment by otvv** [comment]
Nothing new here. I'm making a new framework for my cheat, so... I'm not working on anything new rn.

**Comment by DarkAussieYT** [comment]
Is it public or private?

**Comment by otvv** [comment]
Private.
