### ISSUE TITLE
triggerbot is crashing

### ISSUE THREAD

**Issue by CitronSK** [XBoom31/ApocalyseCheatsSC#4]
fix please :)

**Comment by Azukee** [comment]
Update GetCSWpnDataAddr in Entities.h->756 to
`static DWORD GetCSWpnDataAddr = Utilities::Memory::FindPattern("client.dll", (PBYTE)"\x55\x8B\xEC\x81\xEC\x00\x00\x00\x00\xB8\x00\x00\x00\x00\x57", "xxxxx????x????x");`

**Comment by CitronSK** [comment]
Thanks working not crashing! but when i have triggerbot on key bind then it crashes!
