### ISSUE TITLE
Enemny Only Chams

### ISSUE THREAD

**Issue by Weeeishy** [XBoom31/ApocalyseCheatsSC#46]
Hello,

Has anyone fixed the enemy only chams? I've been trying to remove the commented stuff in hooks.cpp but it crashes my game.

I would appreciate if someone could share a fix to that.

**Comment by XBoom31** [comment]
I've fixed it, but sadly I won't share the source, I've made a more private
version with a client. I'll make that invite only, still free. Sorry.

**Comment by otvv** [comment]
I've tried to fix mine but is still fucked up. Mine still draws when my team gets closer to enemies. 
Weird asf the same thing happens with glow.

**Comment by minhao-retard** [comment]
Thats a pretty easy fix :D will put in pull requests

**Comment by otvv** [comment]
I already got it fixed. ^^

**Comment by minhao-retard** [comment]
good ^^

**Comment by Weeeishy** [comment]
@manhhao I haven't fixed it yet. I would really appreciate if you pull request the fix!
