### ISSUE TITLE
Update offsets please

### ISSUE THREAD

**Issue by DiogoDuart3** [XBoom31/ApocalyseCheatsSC#48]
New csgo update, can someone please tell me how to update the offsets? ty

**Comment by bennoprice** [comment]
Im having the same issue, does your game also crash on injection?

**Comment by bennoprice** [comment]
- - - - - - 
 - Entitys - 
 - - - - - - 

 > LocalPlayer 0x9D3C6C
 > EntityList 0xA42634

 - - - - - - - 
 - RadarBase - 
 - - - - - - - 

 > RadarBase 0xA7707C
 > RadarPointer 0x20
 > RadarHealth 0x20
 > RadarName 0x24
 > RadarSize 0x1EC

 - - - - - - 
 - NetVars - 
 - - - - - - 

 > m_flNextPrimaryAttack 0x14F8
 > m_hOwner 0x14F0
 > m_iState 0x1510
 > m_iClip1 0x151C
 > m_iClip2 0x1520
 > m_hActiveWeapon 0x12C0
 > m_bSpotted 0x935
 > m_hOwnerEntity 0x148
 > m_vecOrigin 0x134
 > m_iTeamNum 0xF0
 > m_Local 0x136C
 > m_vecViewOffset 0x104
 > m_nTickBase 0x17B4
 > m_vecVelocity 0x110
 > m_vecBaseVelocity 0x11C
 > m_lifestate 0x25B
 > m_fFlags 0x100
 > m_iHealth 0xFC
 > m_iFOV 0x1590
 > m_flFlashMaxAlpha 0x1D7C
 > m_flFlashDuration 0x1D80
 > m_angEyeAngles 0x236C
 > m_iAccount 0x235C
 > m_iCrossHairID 0x23C4
 > m_fAccuracyPenalty 0x15D0
 > m_iWeaponID 0x15EC
 > m_vecPunch 0x13DC

 - - - - -
 - Other -
 - - - - -

 > BoneMatrix 0xA78
 > GlobalVars 0x507960
 > EnginePointer 0x507CC4
 > EnginePosition 0x5AF024
 > ViewMatrix 0xA37C94

 Build Date : 8/6/2014 - 12:18:44

 - - - - - - - - - - - - 
 - Tool by Y3t1y3t(uc) - 
 - - - - - - - - - - - - 

 - - - - - - 
 - Entitys - 
 - - - - - - 

 > LocalPlayer 0x9D3C6C
 > EntityList 0xA42634

 - - - - - - - 
 - RadarBase - 
 - - - - - - - 

 > RadarBase 0xA7707C
 > RadarPointer 0x20
 > RadarHealth 0x20
 > RadarName 0x24
 > RadarSize 0x1EC

 - - - - - - 
 - NetVars - 
 - - - - - - 

 > m_flNextPrimaryAttack 0x14F8
 > m_hOwner 0x14F0
 > m_iState 0x1510
 > m_iClip1 0x151C
 > m_iClip2 0x1520
 > m_hActiveWeapon 0x12C0
 > m_bSpotted 0x935
 > m_hOwnerEntity 0x148
 > m_vecOrigin 0x134
 > m_iTeamNum 0xF0
 > m_Local 0x136C
 > m_vecViewOffset 0x104
 > m_nTickBase 0x17B4
 > m_vecVelocity 0x110
 > m_vecBaseVelocity 0x11C
 > m_lifestate 0x25B
 > m_fFlags 0x100
 > m_iHealth 0xFC
 > m_iFOV 0x1590
 > m_flFlashMaxAlpha 0x1D7C
 > m_flFlashDuration 0x1D80
 > m_angEyeAngles 0x236C
 > m_iAccount 0x235C
 > m_iCrossHairID 0x23C4
 > m_fAccuracyPenalty 0x15D0
 > m_iWeaponID 0x15EC
 > m_vecPunch 0x13DC

 - - - - -
 - Other -
 - - - - -

 > BoneMatrix 0xA78
 > GlobalVars 0x507960
 > EnginePointer 0x507CC4
 > EnginePosition 0x5AF024
 > ViewMatrix 0xA37C94

**Comment by bennoprice** [comment]
**these are the offsets but i dont know how to implement them**
