### ISSUE TITLE
Updated Offsets

### ISSUE THREAD

**Issue by GenoSans** [XBoom31/ApocalyseCheatsSC#50]
plz fix b1g bug

**Comment by iFloody** [comment]
How about you fix it by yourself?

**Comment by GenoSans** [comment]
do i look like a coder to you

**Comment by iFloody** [comment]
Just stop using this then. Why the fuck do you download a source code and don't learn anything from it? Changing offsets is easy asf, even a guy who is not a coder can change that. Just google it.

**Comment by GenoSans** [comment]
rage aimbot crashes. everything else works fine

**Comment by GenoSans** [comment]
bruh

**Comment by iFloody** [comment]
Dude Valve fucked everything in that update. Just wait for someone to fix it.

**Comment by Aplexy** [comment]
**Change in Hooks.cpp, Fixes Skin changer**

**Old**
```
if (!(sWeapon.find("models/weapons", 0) != std::string::npos))
continue;
```

**New**
```
if (sWeapon.find("models/weapons", 0) != std::string::npos)
continue;
```

**Change in Entities.h**

**Old**
`Functions::KeyValues_LoadFromBuffer = Utilities::Memory::FindPattern("client.dll", (PBYTE)"\xE8\x00\x00\x00\x00\x8A\xD8\xFF\x15\x00\x00\x00\x00\x84\xDB", "x????xxxx????xx");`

**New**
`Functions::KeyValues_LoadFromBuffer = Utilities::Memory::FindPattern("client.dll", (PBYTE)"\xE8\x00\x00\x00\x00\x80\x7D\xF8\x00\x00\x00\x85\xDB", "x????xxxx??xx");`


should fix most of your problems

**Comment by ChillyLV** [comment]
CS:GO Still crashes when injecting. :/
