### ISSUE TITLE
Crush while using MASSAS resolver and Resolver

### ISSUE THREAD

**Issue by 84z0r** [XBoom31/ApocalyseCheatsSC#53]
Crush while using MASSAS resolver and Resolver

**Comment by whoami110** [comment]
yea same thing here and resolver 2 some time shot fake and resolver 1 sometime crash

**Comment by XBoom31** [comment]
Idk, it does not crash for everyone, for me no, idk how to fix it if does
not crash for me

**Comment by whoami110** [comment]
Xboom
Iam compailing with vs2015 entirpeise 
Are compailing with diffrente version

Idk if it make any diffrente
 But when i choose massa resolvee every think freez i have to end the proccess to close it
And resolver 1 freez the game when u see enemy player

**Comment by XBoom31** [comment]
It crashes randomly with the same compiled version, a resolver never
crashed for me, idk why

**Comment by whoami110** [comment]
Can u try to compile the version on the realse and tested i think last update crashed him

**Comment by XBoom31** [comment]
Hmm, I have an ideea that could fix that once and forever, I need your
help, add me on steam /id/petreusxd

**Comment by whoami110** [comment]
I added u name is and..

**Comment by whoami110** [comment]
Xboom i added u steam name is and..
Id/matthew10

**Comment by whoami110** [comment]
@XBoom31  u still here mate what do u think we should do..
