### ISSUE TITLE
Error when building Apocalypse. Please help!

### ISSUE THREAD

**Issue by moneyfraud** [XBoom31/ApocalyseCheatsSC#54]
I updated everything. Now when i build it shows me the following error: 'm_flRange': is not a member of 'CSWeaponInfo' in RageBot.cpp. Please help! Everything is appreaciated! Btw im a noob in hacking and coding and stuff. Thanks again!

**Comment by otvv** [comment]
Just go to your csweapon and search for flrange. The name changed.

**Comment by moneyfraud** [comment]
I'm retarded, Can you please explain with more details? Thanks.

**Comment by moneyfraud** [comment]
Nvm, i figured it out. Sorry, im dumb.
