### ISSUE TITLE
Configs aren't working! Please help!

### ISSUE THREAD

**Issue by moneyfraud** [XBoom31/ApocalyseCheatsSC#56]
Noob here! So, i updated all my offsets and everything is working. Except configs. I tried deleting saves from the CS:GO folder, didn't help! Please help me! Thanks!

**Comment by moneyfraud** [comment]
Has anyone even seen this issue? :D

**Comment by jensuss** [comment]
if your tabs are named "legit bot" then name them "legitbot" cus spaces may cause configs to not load.

**Comment by moneyfraud** [comment]
Will try. Thanks. I will respond if it works.

**Comment by moneyfraud** [comment]
Worked thanks. Closing the issue.
