### ISSUE TITLE
Offsets and crash

### ISSUE THREAD

**Issue by nijmaz** [XBoom31/ApocalyseCheatsSC#57]
Hi im new to c++ but im trying to learn so i was wondering how to update the offsets i have searched but i cannot find how to thanks in advanse.

**Comment by jensuss** [comment]
learncpp.com

**Comment by moneyfraud** [comment]
I can upload updated offsets file to mega.nz and send the link to you, if you want to.

**Comment by GenoSans** [comment]
ChillyLV yes pls

**Comment by GenoSans** [comment]
I Can give you the fixed Offsets.h if you want @nijmaz

**Comment by XBoom31** [comment]
The offsets are all over the place in ayymeme, not only in offsets.h

**Comment by XBoom31** [comment]
Uploading it won't help you at all, search on uc for the offsets u want,
you can find what's wrong by debugging the cheat by testing every feature
and see what crashes. After you found them, just copy the name of the
function and search it on uc, after the copy pasta the value and your cheat
should work fine. It's a bit time consuming, you should find some fix tuts
for everything you need to change if you are that lazy to test.
