### ISSUE TITLE
VAC ERROR

### ISSUE THREAD

**Issue by whoami110** [XBoom31/ApocalyseCheatsSC#58]
IAM USING LEGIT SETTING AFTER SOME TIME I GOT THIS 

Disconnected by VAC: You cannot play on secure servers 
and they reference this page https://support.steampowered.com/kb_article.php?ref=2117-ILZV-2837#explanation

idon,t use skinchagner only legit with box and name

**Comment by DarkAussieYT** [comment]
This cheat is detected, you got vacced

**Comment by moneyfraud** [comment]
For me it works fine. Try exiting out of Steam, and opening Steam as an adminstrator.
