### ISSUE TITLE
Knifechanger issues.

### ISSUE THREAD

**Issue by moneyfraud** [XBoom31/ApocalyseCheatsSC#65]
So... The knife-changer works, for like 1 round. In the next round it starts dissapearing and in the 3 round its  completely gone. Please help... Noob here so please talk in understandable language :D Once i get it fixed i will close this issue.. :) Thanks! Everything is appreaciated!

**Comment by GenoSans** [comment]
klick apply 👎

**Comment by moneyfraud** [comment]
Yeah, but  i dont want to do it 100000 times. Before the CS:GO update this issue wasn't a thing.

**Comment by imaJLOL** [comment]
do m_hMyWeapons loop instead of entire entity loop. This fixed the issue.

**Comment by whoami110** [comment]
@imaJLOL  can u give more info about that ...

**Comment by moneyfraud** [comment]
Yeah, please explain in which file do i change it? Thanks.

**Comment by moneyfraud** [comment]
bump

**Comment by moneyfraud** [comment]
bump?
