### ISSUE TITLE
Ragebot auto shoot not working! Please help! :)

### ISSUE THREAD

**Issue by moneyfraud** [XBoom31/ApocalyseCheatsSC#68]
So for the ragebot auto shoot feature doesn't work. :/ Can anyone help me fix this issue? Everything is appreaciated. :)

**Comment by miheg123** [comment]
Dude you literally want spoonfeed 24/7

**Comment by moneyfraud** [comment]
Can you please explain what does spoonfeed mean?

**Comment by miheg123** [comment]
You open a thread everytime you have something wrong in your code and waiting for some pastable codes that's what spoonfeed mean

**Comment by whoami110** [comment]
Ragebot  work find tested today.....
just redownload the project and compile ..

don,t edit stuff u don,t know what it doese ...

**Comment by moneyfraud** [comment]
I'll try, if works i will remove this issue.

**Comment by moneyfraud** [comment]
Btw im not the only one that is having this issue. Watch this from the part where he starts playing: https://www.youtube.com/watch?v=Zzo5Bw-w1uE . Watch from 8:40.

**Comment by XBoom31** [comment]
that is the first ever relased verison on uc, this works, try disabling the auto stop, crouch

**Comment by moneyfraud** [comment]
Okey, will try. Thanks!
