### ISSUE TITLE
Needs fix Spinbots

### ISSUE THREAD

**Issue by psxsahan** [XBoom31/ApocalyseCheatsSC#9]
Needs fix Spinbots

**Comment by psxsahan** [comment]
+ skinchanger not working in CT

**Comment by psxsahan** [comment]
player chams color not changes

**Comment by psxsahan** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"void __cdecl SetClanTag(char const *,char const *)" (?SetClanTag@@YAXPBD0@Z) already defined in Hooks.obj	Apocalypse	1

**Comment by Ellcz** [comment]
"already defined in Hooks.obj".... You have clantagchanger defined in hooks.cpp and MiscHacks.cpp.. Delete clantagchanger from MiscHacks.cpp.

**Comment by shikarrr257** [comment]
@Ellcz that wont work for me, if I delete clantagchanger in mischacks.cpp i get error: SetClanTag is not defined

**Comment by Ellcz** [comment]
IT works. I just did it? No problemo. :D Maybe you did something wrong.

**Comment by CyclesProgramming** [comment]
#11 
fixed the clan tag error and the chams not taking color from the tab
